#!/bin/bash

sudo cp locationchanger /usr/local/bin
#sudo cp wifionoff /usr/local/bin

sudo cp com.networkutilities.locationchanger.plist ~/Library/LaunchAgents/
#sudo cp com.networkutilities.wifionoff.plist ~/Library/LaunchAgents/

sudo chown root:wheel ~/Library/LaunchAgents/com.networkutilities.locationchanger.plist
#sudo chown root:wheel ~/Library/LaunchAgents/com.networkutilities.wifionoff.plist

chmod o-w ~/Library/LaunchAgents/*
launchctl load ~/Library/LaunchAgents/com.networkutilities.locationchanger.plist
#launchctl load ~/Library/LaunchAgents/com.networkutilities.wifionoff.plist
