#!/bin/bash

cp locationchanger /usr/local/bin
cp com.networkutilities.locationchanger.plist ~/Library/LaunchAgents/
launchctl load ~/Library/LaunchAgents/com.networkutilities.locationchanger.plist

cp wifionoff /usr/local/bin
chmod 755 /usr/local/bin/wifionoff
cp com.networkutilities.wifionoff.plist /Library/LaunchDaemons/
chown root:wheel /Library/LaunchDaemons/com.networkutilities.wifionoff.plist